---
- name: Install Vagrant
  apt: pkg=vagrant state=present update_cache=yes
  become: yes

- name: Add virtualbox repository
  apt_repository: 
      repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
      state: present
  become: yes

- name: Adding apt-key for the added repository
  apt_key: 
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
  become: yes

- name: Install Virtualbox
  apt: pkg=virtualbox-5.0 state=present update_cache=yes
  become: yes
  
- name: Ensure directory exists
  file: path={{ ansible_env.HOME }}/{{vm_ip}} state=directory

- name: Copying trusty64's Vagrantfile
  template: src=Vagrantfile.j2 dest={{ ansible_env.HOME }}/{{vm_ip}}/Vagrantfile

- name: Creating a VM using vagrant
  shell: cd {{ ansible_env.HOME }}/{{vm_ip}}; vagrant up
  register: command_result
  changed_when: 'command_result.stdout.find("VirtualBox VM is already running") == -1'

- name: Wait for the VM to boot up to SSH
  pause:
    seconds: 20
...
