---
- name: Download Jenkins CLI jar file
  get_url:
    url: http://{{ jenkins_ip }}:{{ jenkins_port }}/jnlpJars/jenkins-cli.jar
    dest: '{{ jenkins_cli_jar_loc }}/.'

- name: Install the package "npm"
  apt:
    name: npm
    state: present
  become: yes

- name: Create a template xml file for Jenkins checkbox build job
  template: src=build_xml.j2 dest=/tmp/checkbox_temp.xml

- name: Update Sudoers file for Jenkins User
  lineinfile:
    dest: /etc/sudoers
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
  become: yes

- name: Check if job exists
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ list-jobs --username {{jenkins_username}} --password {{jenkins_password}}"
  register: jenkins_cb_stat

- name: create jenkins jobs with xml files
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ create-job {{jenkins_checkbox_job_name}} < /tmp/checkbox_temp.xml --username {{jenkins_username}} --password {{jenkins_password}}"
  when: jenkins_cb_stat.stdout.find(jenkins_checkbox_job_name)==-1

- name: Extract build location
  lineinfile:
    path: "{{jobs_extract_location}}/app_deploy/roles/checkboxSetup/vars/main.yml"
    line: "checkBoxRepoLocation: /var/lib/jenkins/jobs/{{jenkins_checkbox_job_name}}/workspace/"
    state: present

- name: Build Jenkins Job for Checkbox_io
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ build {{jenkins_checkbox_job_name}} --username {{jenkins_username}} --password {{jenkins_password}} -s"