---
- name: install Java
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become: yes

- name: install java8
  shell: apt install -y oracle-java8-installer ca-certificates
  become: yes

- name: Install the package "maven"
  apt:
    name: maven
    state: present

- name: Install git
  apt: name=git state=present

- name: Ensure file exists
  copy:
    content: ""
    dest: /tmp/itrust_temp.xml
    force: yes

- name: Create a template file for iTrust build job
  template: src=build_xml.j2 dest=/tmp/itrust_temp.xml

- name: Update Sudoers file for Jenkins User
  lineinfile:
    dest: /etc/sudoers
    line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
  become: yes

- name: Check if job exists
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ list-jobs --username {{jenkins_username}} --password {{jenkins_password}}"
  register: jenkins_it_stat

- name: create jenkins jobs with xml files
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ create-job {{ jenkins_iTrust_job_name }} < /tmp/itrust_temp.xml --username {{jenkins_username}} --password {{jenkins_password}}"
  when: jenkins_it_stat.stdout.find(jenkins_iTrust_job_name)==-1

- name: Extract build location
  lineinfile:
    path: "{{jobs_extract_location}}/app_deploy/roles/iTrustDeploy/vars/main.yml"
    line: "iTrustRepoLocation: /var/lib/jenkins/jobs/{{jenkins_iTrust_job_name}}/workspace/iTrust-v23/iTrust/"
    state: present

- name: Build Jenkins Job for iTrust
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ build {{ jenkins_iTrust_job_name }} --username {{jenkins_username}} --password {{jenkins_password}} -s"