- name: "Installing maven"
  apt: package="maven" state="present"
  become: yes

# Copy module for 1k+ files takes longer. Use rsync instead
- name: "Copying required iTrust files for building"
  synchronize:
    src: "{{iTrustRepoLocation}}"
    dest: "{{iTrustTempLocation}}"

- name: "Building war file for iTrust"
  command: "mvn package -DskipTests"
  args:
    chdir: "{{iTrustTempLocation}}"
  become: yes